### ISSUE TITLE
Changed Bytes Colors

### ISSUE THREAD

**Issue by norisyaza555** [learn-more/MemView#3]
Nice Project but (on bytes changed color) not work in windows 10 x64 please fix 
MainWnd >> info.changed / lplvcd->clrText = RGB(255, 0, 0);

**Comment by learn-more** [comment]
@norisyaza555 can you elaborate on this, any specific application / test case?
It works fine for me testing on memview itself:

![image](https://github.com/learn-more/MemView/assets/610685/0da229db-99d4-46a3-ab30-f239d133557b)

**Comment by norisyaza555** [comment]
!Not here in Memory View Please add Change Color of Changing Bytes
I will use your project on something similar to watch Android application memory with the use of adb/socket 
thanks you. 

![Alt Text](https://i.ibb.co/hCbJ9g4/ezgif-com-gif-maker.gif)

**Comment by learn-more** [comment]
Thanks for reporting, this should be fixed in the next release:

![image](https://github.com/learn-more/MemView/assets/610685/dfcde8b7-c25e-4fe9-a807-939448a1996c)
